const express = require("express")
const createBatter = require('../../controller/model relationShip/referencing/batterCreate')
const createTeam = require('../../controller/model relationShip/referencing/createTeam')
const teamInfo = require('../../controller/model relationShip/referencing/teamInfo')
const createEMTeam = require('../../controller/model relationShip/embedding/createEMTeam')
const createEMBatter = require('../../controller/model relationShip/embedding/createEMBatter')
const createEMBatterWithArr = require('../../controller/model relationShip/embedding/createEMBatterwithArr')
const addembatterwitharr = require('../../controller/model relationShip/embedding/addEMBatterwithArr')
const removeEMBatterwithArr = require('../../controller/model relationShip/embedding/removeEMBatterwithArr')
const _ = express.Router()

_.post("/createembatter",createEMBatter)
_.post("/createembatterwitharr",createEMBatterWithArr)
_.delete("/removeemateam",removeEMBatterwithArr)
_.post("/addembatterwitharr",addembatterwitharr)
_.post("/createbatter",createBatter)
_.post("/createteam",createTeam)
_.post("/createemteam",createEMTeam)
_.get("/teaminfo",teamInfo)

module.exports = _